server:
  http_port: 8080
  rpc_port: 9090
  mode: dev

database:
  driver: mysql
  dsn: root:passwd@tcp(127.0.0.1:33060)/test_db?charset=utf8mb4&parseTime=True&loc=Local
  auto_migrate: true

redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0

log:
  level: info
  format: json


