// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-sweets/sweets-layout/internal/boundedcontexts/hello/application/handlers"
	"github.com/go-sweets/sweets-layout/internal/config"
	"github.com/go-sweets/sweets-layout/internal/di/providers"
	"github.com/go-sweets/sweets-layout/internal/di/providers/hello"
	"github.com/go-sweets/sweets-layout/internal/server"
	"github.com/go-sweets/sweets-layout/internal/service"
)

// Injectors from wire.go:

// initApp init app application.
func initApp(c *config.Config) (*server.AppServer, error) {
	db, err := providers.NewGormDB(c)
	if err != nil {
		return nil, err
	}
	userRepository := hello.NewUserRepository(db)
	helloGrpcHandler := handlers.NewHelloGrpcHandler(userRepository)
	helloService := service.NewHelloService(helloGrpcHandler)
	serviceRegistrar := providers.NewServiceRegistrar(helloService)
	hertz := server.NewHertzServer(c, helloService)
	serverServer := server.NewKitexServer(c, serviceRegistrar)
	appServer, err := server.NewApp(c, serviceRegistrar, hertz, serverServer)
	if err != nil {
		return nil, err
	}
	return appServer, nil
}
